project:
  type: website

website:
  title: Impact of Urban Activity on Air Quality
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-Fall25-101-201/final-project-w-squared-watts-wowk
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
